### ISSUE TITLE
is the 0.3.x branch still active?

### ISSUE THREAD

**Issue by modosc** [zalmoxisus/remotedev-server#37]
i really find this code useful to debug ssr. i've noticed a lot of deprecation warnings centered around `apollo-server`:
```
warning remotedev-server > apollo-server@0.3.3: apollo-server has been renamed. The package is now called GraphQL Server. Please download the package for your specific server. Install graphql-server-<name> where name is one of the available server integrations: express, hapi, koa, restify, lambda
warning remotedev-server > node-uuid@1.4.8: Use uuid module instead
warning remotedev-server > knex > node-uuid@1.4.8: Use uuid module instead
```

is this project still being actively maintained? if so, would you be open to a pr to resolve the above issues?

**Comment by zalmoxisus** [comment]
Hey @modosc,

Yes, a pr to update `apollo-server` would be much appreciated.

The problem however is with `knex` (which requires `node-uuid@1.4.8`). We're using an old version because `0.12` [broke support for in memory sqlite database](https://github.com/tgriesser/knex/issues/1701#issuecomment-269992685). A possible workaround is suggested [here](https://github.com/tgriesser/knex/issues/1871#issuecomment-273721116), but I'd prefer to keep a stable (for this purpose) version.

**Comment by modosc** [comment]
got it - #39 updates everything else except `knex`
